config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "employees#index"
  resources :departments
  resources :employees
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
  validates_uniqueness_of :name
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  validates :name, presence: true, length: { minimum: 3 }
  
  def self.search(search)
    where("name ILIKE ?", "#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!
    include Pagy::Backend
    add_flash_types :danger
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :find_department, except: [:index, :new, :create]

  def index
    @departments = Department.all
  end

  def new; end

  def show; end

  def edit; end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to employees_path
    else
      redirect_to new_department_path, danger: "Such department already exist"
    end
  end

  def update
    if @department.update(department_params)
      redirect_to departments_path
    else
      redirect_to edit_department_path, danger: "Such department already exist"
    end
  end

  def destroy
    @department.destroy

    redirect_to departments_path
  end

  private

  def find_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, except: [:index, :new, :create]

  def index
    filtered = if params[:search].present?
                  Employee.search(params[:search])
              else
                  Employee.all
              end
    @pagy, @employees = pagy(filtered, items: 4)
  end

  def new; end

  def show; end

  def edit; end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path
    else
      render 'new'
    end
  end

  def update
    @employee.update(employee_params)

    redirect_to employees_path
  end

  def destroy
    @employee.destroy

    redirect_to root_path
  end

  private

  def find_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :active, :department_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/departments/edit.html.erb
<div class="row p-3 px-md-4">
  <div class="col-lg-3">
    <%= form_for @department, url: department_path do |f| %>
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <%= f.submit "Save", class: "btn btn-primary" %>
      <%= link_to "Back", departments_path, class: "btn btn-light" %>
    <% end %>
  </div>
</div>

app/views/departments/index.html.erb
<div class="col-lg-6 p-3">
<p>
  <%= link_to "Add employee", new_employee_path, class: 'btn btn-sm btn-primary' %>
  <%= link_to "Add department", new_department_path, class: 'btn btn-sm btn-primary' %>
</p>
<div>
  <%= form_tag employees_path, method: 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", name: nil %>
  <% end %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do |d| %>
    <tr>
      <td><%= d.id %></td>
      <td><%= d.name %></td>
      <td><%= link_to 'Delete', department_path(d), method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'btn btn-light'%>
        <%= link_to('Edit', edit_department_path(d), class: 'btn btn-light') %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/departments/new.html.erb
<div class="row p-3 px-md-2">
  <div class="col-lg-2">
    <%= form_for (Department.new), url: departments_path do |f| %>
      <div class="form-group">
        <%= f.label "Department name" %><br>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
      <%= f.submit "Save", class: "btn btn-primary" %>
      <%= link_to "Back", root_path, class: "btn btn-light" %>
    <% end %>
    </div>
</div>

app/views/employees/edit.html.erb
<div class="row p-3 col px-md-5">
  <%= form_for (@employee), url: employee_path do |f| %>
    <div class="form-group">
      <%= f.label "Name" %>
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= f.collection_select :department_id, Department.all, :id, :name, { prompt: 'Choose category' }, { class: "form-control", required: true } %>
    </div>
    <div class="form-group">
      <%= f.label "Active" %>
      <%= f.check_box :active, {}, 'yes', 'no' %>
    </div>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", employees_path, class: "btn btn-light" %>
  <% end %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-6 p-3">
<p>
  <%= link_to "Add employee", new_employee_path, class: 'btn btn-sm btn-primary' %>
  <%= link_to "Add department", new_department_path, class: 'btn btn-sm btn-primary' %>
</p>
<div>
  <%= form_tag employees_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Active</th>
      <th scope="col">Department</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employee.each do |e| %>
    <tr>
      <td><%= e.id %></td>
      <td><%= e.name %></td>
      <td><%= e.active %></td>
      <td><%= e.department.name %></td>
      <td><%= link_to 'Delete', employee_path(e), method: :delete,
        data: {:confirm => 'Are you sure?'}, class: 'btn btn-light'%>
        <%= link_to('Edit', edit_employee_path(e), class: 'btn btn-light') %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/employees/new.html.erb
<div class="row p-3 col px-md-4">
  <div class="col-sm-3 p-3 border bg-light">
    <%= form_for (Employee.new), url: employees_path do |f| %>
      <div class="form-group">
        <%= f.label "Name" %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= f.collection_select :department_id, Department.all, :id, :name, { prompt: 'Choose category' }, { class: "form-control", required: true } %>
      </div>
      <div class="form-group">
        <%= f.label "Active" %>
        <%= f.check_box :active, {}, 'yes', 'no' %>
      </div>
      <%= f.submit "Save", class: "btn btn-primary" %>
      <%= link_to "Back", employees_path, class: "btn btn-light" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>